language: generic

sudo: required

services: docker

#git:
#  clone: false
#  - ssh-keyscan 1.1.1.1 >> $HOME/.ssh/known_hosts

install:
  - openssl aes-256-cbc -K $encrypted_12f1486e37a0_key -iv $encrypted_12f1486e37a0_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
script:
  - ping -c 3 google.com
