language: generic

sudo: required

services:
  - docker

git:
  clone: false
  - ssh-keyscan 1.1.1.1 >> $HOME/.ssh/known_hosts

install:
  - cd $TRAVIS_PULL_REQUEST_SLUG
  - openssl aes-256-cbc -K $encrypted_12f1486e37a0_key -iv $encrypted_12f1486e37a0_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  #- bash ./autocheck.sh queue $TEST_IP
script:
  - ping -c 3 google.com
  #- ssh -i skey cland@$TEST_IP "cd /opt/cloudland/ && sudo bash ./autocheck.sh pull_request
  #$TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_SLUG"
  #- bash ./autocheck.sh test $TEST_IP
